"""add deep logo field

Revision ID: 43709240f10d
Revises: b8401c08230a
Create Date: 2024-11-15 12:14:10.560080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43709240f10d'
down_revision: Union[str, None] = 'b8401c08230a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newfilters', sa.Column('deep_logo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newfilters', 'deep_logo')
    # ### end Alembic commands ###
