"""init

Revision ID: a7267c125b4d
Revises: 39d6615aae95
Create Date: 2024-10-09 19:12:44.771851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7267c125b4d'
down_revision: Union[str, None] = '39d6615aae95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newfilters', sa.Column('replacement', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newfilters', 'replacement')
    # ### end Alembic commands ###
