"""add flag

Revision ID: bb557d98979a
Revises: ee8dbf951910
Create Date: 2024-11-16 01:21:31.071999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb557d98979a'
down_revision: Union[str, None] = 'ee8dbf951910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newfilters', sa.Column('only_first_logo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newfilters', 'only_first_logo')
    # ### end Alembic commands ###
