"""save abcp

Revision ID: 519834e30fc5
Revises: bb557d98979a
Create Date: 2024-11-18 20:45:37.162305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519834e30fc5'
down_revision: Union[str, None] = 'bb557d98979a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsers', sa.Column('abcp_price', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parsers', 'abcp_price')
    # ### end Alembic commands ###
