"""check revision

Revision ID: 82dc47e196bf
Revises: 8ba15696f861
Create Date: 2024-09-06 00:24:01.375520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82dc47e196bf'
down_revision: Union[str, None] = '8ba15696f861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsers', sa.Column('best_price', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('delivery_time', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('new_price', sa.String(), nullable=True))
    op.drop_column('parsers', 'deliveryTime')
    op.drop_column('parsers', 'bestPrice')
    op.drop_column('parsers', 'newPrice')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsers', sa.Column('newPrice', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('parsers', sa.Column('bestPrice', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('parsers', sa.Column('deliveryTime', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('parsers', 'new_price')
    op.drop_column('parsers', 'delivery_time')
    op.drop_column('parsers', 'best_price')
    # ### end Alembic commands ###
