"""edit parser

Revision ID: 0a4481eb1f77
Revises: 2b272960d33c
Create Date: 2024-09-05 19:32:21.130663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4481eb1f77'
down_revision: Union[str, None] = '2b272960d33c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsers', sa.Column('name', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('brand', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('article1', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('quantity', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('price', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('batch', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('nds', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('best_price', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('delivery_time', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('new_price', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('quantity1', sa.String(), nullable=False))
    op.drop_column('parsers', 'quantity_goods')
    op.drop_column('parsers', 'best_price')
    op.drop_column('parsers', 'price_with_logo')
    op.drop_column('parsers', 'number_of_goods')
    op.drop_column('parsers', 'delivery')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsers', sa.Column('delivery', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('parsers', sa.Column('number_of_goods', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('parsers', sa.Column('price_with_logo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('parsers', sa.Column('best_price', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('parsers', sa.Column('quantity_goods', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('parsers', 'quantity1')
    op.drop_column('parsers', 'new_price')
    op.drop_column('parsers', 'delivery_time')
    op.drop_column('parsers', 'best_price')
    op.drop_column('parsers', 'nds')
    op.drop_column('parsers', 'batch')
    op.drop_column('parsers', 'price')
    op.drop_column('parsers', 'quantity')
    op.drop_column('parsers', 'article1')
    op.drop_column('parsers', 'brand')
    op.drop_column('parsers', 'name')
    # ### end Alembic commands ###
