"""edit parser table

Revision ID: 78f6f941b593
Revises: 204dea88770b
Create Date: 2024-08-19 12:01:02.192023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78f6f941b593'
down_revision: Union[str, None] = '204dea88770b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsers', sa.Column('quantity_goods', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('price_with_logo', sa.String(), nullable=True))
    op.drop_column('parsers', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsers', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('parsers', 'price_with_logo')
    op.drop_column('parsers', 'quantity_goods')
    # ### end Alembic commands ###
