"""add nullable

Revision ID: f33b1e1e7d20
Revises: f906c13633f8
Create Date: 2024-09-05 23:29:28.402746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f33b1e1e7d20'
down_revision: Union[str, None] = 'f906c13633f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parsers', 'new_price',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('parsers', 'quantity1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parsers', 'quantity1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('parsers', 'new_price',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
