"""add after_vat_price

Revision ID: c6978d90d9d8
Revises: 4000abc25fd8
Create Date: 2024-09-12 15:13:15.465408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6978d90d9d8'
down_revision: Union[str, None] = '4000abc25fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsers', sa.Column('after_vat_price', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parsers', 'after_vat_price')
    # ### end Alembic commands ###
