"""init

Revision ID: d555cc47d601
Revises: 944c47225287
Create Date: 2024-09-07 11:31:53.727960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd555cc47d601'
down_revision: Union[str, None] = '944c47225287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('newfilters', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('parsers', sa.Column('name', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('brand', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('article1', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('quantity', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('price', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('batch', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('nds', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('delivery_time', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('new_price', sa.String(), nullable=True))
    op.add_column('parsers', sa.Column('quantity1', sa.String(), nullable=False))
    op.add_column('parsers', sa.Column('file_id', sa.Integer(), nullable=True))
    op.alter_column('parsers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'parsers', 'files', ['file_id'], ['id'])
    op.drop_column('parsers', 'quantity_goods')
    op.drop_column('parsers', 'price_with_logo')
    op.drop_column('parsers', 'delivery')
    op.drop_column('parsers', 'number_of_goods')
    op.alter_column('proxys', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proxys', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('parsers', sa.Column('number_of_goods', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('parsers', sa.Column('delivery', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('parsers', sa.Column('price_with_logo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('parsers', sa.Column('quantity_goods', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'parsers', type_='foreignkey')
    op.alter_column('parsers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('parsers', 'file_id')
    op.drop_column('parsers', 'quantity1')
    op.drop_column('parsers', 'new_price')
    op.drop_column('parsers', 'delivery_time')
    op.drop_column('parsers', 'nds')
    op.drop_column('parsers', 'batch')
    op.drop_column('parsers', 'price')
    op.drop_column('parsers', 'quantity')
    op.drop_column('parsers', 'article1')
    op.drop_column('parsers', 'brand')
    op.drop_column('parsers', 'name')
    op.alter_column('newfilters', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('files', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
