"""different file in parser saving

Revision ID: 3f6541bded6d
Revises: 019b3f0b5a7f
Create Date: 2024-08-29 22:50:48.940103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f6541bded6d'
down_revision: Union[str, None] = '019b3f0b5a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsers', sa.Column('file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parsers', 'files', ['file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parsers', type_='foreignkey')
    op.drop_column('parsers', 'file_id')
    # ### end Alembic commands ###
