"""check revision

Revision ID: 8ba15696f861
Revises: 8afe553544ad
Create Date: 2024-09-06 00:22:58.016039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba15696f861'
down_revision: Union[str, None] = '8afe553544ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsers', sa.Column('nds', sa.String(), nullable=False))
    op.drop_column('parsers', 'NDS')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsers', sa.Column('NDS', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('parsers', 'nds')
    # ### end Alembic commands ###
