"""delete deep logo

Revision ID: ee8dbf951910
Revises: 43709240f10d
Create Date: 2024-11-15 13:25:32.626391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee8dbf951910'
down_revision: Union[str, None] = '43709240f10d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newfilters', 'deep_logo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newfilters', sa.Column('deep_logo', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
