"""add title in filters

Revision ID: 204dea88770b
Revises: b06d3021258c
Create Date: 2024-08-18 15:58:05.196209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '204dea88770b'
down_revision: Union[str, None] = 'b06d3021258c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newfilters', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newfilters', 'title')
    # ### end Alembic commands ###
