"""add nullable

Revision ID: f906c13633f8
Revises: 8cddb63cbbf3
Create Date: 2024-09-05 23:27:59.977167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f906c13633f8'
down_revision: Union[str, None] = '8cddb63cbbf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parsers', 'quantity1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parsers', 'quantity1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
