"""add date ban proxy

Revision ID: a36271268f6e
Revises: 78f6f941b593
Create Date: 2024-08-22 13:29:22.940663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36271268f6e'
down_revision: Union[str, None] = '78f6f941b593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxys', sa.Column('when_banned', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxys', 'when_banned')
    # ### end Alembic commands ###
