"""nullable=true

Revision ID: 2b272960d33c
Revises: 3f6541bded6d
Create Date: 2024-08-31 18:03:19.514902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b272960d33c'
down_revision: Union[str, None] = '3f6541bded6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('newfilters', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('parsers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('proxys', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proxys', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('parsers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('newfilters', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('files', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
