"""init

Revision ID: 1e9699d1c9d9
Revises: a7267c125b4d
Create Date: 2024-10-09 19:14:32.189068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e9699d1c9d9'
down_revision: Union[str, None] = 'a7267c125b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('newfilters', 'replacement',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('newfilters', 'replacement',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
