"""add field in proxy

Revision ID: 019b3f0b5a7f
Revises: 78f6f941b593
Create Date: 2024-08-23 19:49:33.166217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '019b3f0b5a7f'
down_revision: Union[str, None] = '78f6f941b593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxys', sa.Column('is_using', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxys', 'is_using')
    # ### end Alembic commands ###
