"""add name in proxy model

Revision ID: eae903779bf2
Revises: bcb4be5ad607
Create Date: 2025-06-15 12:12:35.833823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae903779bf2'
down_revision: Union[str, None] = 'bcb4be5ad607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxybrightdatas', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxybrightdatas', 'name')
    # ### end Alembic commands ###
