"""edit user table

Revision ID: 9e9000e82892
Revises: 5fa0b03ce95a
Create Date: 2024-07-24 17:00:41.745498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9000e82892'
down_revision: Union[str, None] = '5fa0b03ce95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_user', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
