"""edit proxy

Revision ID: 45036f1c2834
Revises: 04fdc0845bc0
Create Date: 2024-08-02 23:52:38.983871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45036f1c2834'
down_revision: Union[str, None] = '04fdc0845bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxys', sa.Column('_is_banned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxys', '_is_banned')
    # ### end Alembic commands ###
