"""create table filters

Revision ID: 372a65c7f3f3
Revises: c5295ef67947
Create Date: 2024-07-29 21:04:07.131277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372a65c7f3f3'
down_revision: Union[str, None] = 'c5295ef67947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filters',
    sa.Column('is_has_logo', sa.Boolean(), nullable=False),
    sa.Column('logo', sa.String(length=4), nullable=False),
    sa.Column('is_has_brand', sa.Boolean(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('is_bigger_then_date', sa.Boolean(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filters')
    # ### end Alembic commands ###
