"""add date parser table

Revision ID: 04fdc0845bc0
Revises: eaa7c0890995
Create Date: 2024-08-02 19:28:22.790356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04fdc0845bc0'
down_revision: Union[str, None] = 'eaa7c0890995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsers', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parsers', 'date')
    # ### end Alembic commands ###
