"""create parser table

Revision ID: eaa7c0890995
Revises: ba4f8cf449a5
Create Date: 2024-08-02 19:19:45.796034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa7c0890995'
down_revision: Union[str, None] = 'ba4f8cf449a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsers',
    sa.Column('article', sa.String(), nullable=False),
    sa.Column('number_of_goods', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=False),
    sa.Column('delivery', sa.String(), nullable=False),
    sa.Column('best_price', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parsers')
    # ### end Alembic commands ###
