"""edit proxy 2

Revision ID: 83468e1f4380
Revises: 45036f1c2834
Create Date: 2024-08-02 23:53:29.465224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83468e1f4380'
down_revision: Union[str, None] = '45036f1c2834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxys', 'is_banned')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxys', sa.Column('is_banned', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
