"""edit users table

Revision ID: 721cc521c8fa
Revises: 1c08cfd9fe51
Create Date: 2024-07-31 17:12:18.756769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '721cc521c8fa'
down_revision: Union[str, None] = '1c08cfd9fe51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_parsing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_parsing')
    # ### end Alembic commands ###
