import psycopg2
import os

from datetime import datetime
from psycopg2 import sql
from dotenv import load_dotenv

from app.api_v1.auth.utils import hash_password
from app.core.config import settings


load_dotenv()

tables = ["files", "parsers", "proxys"]

db_config = {
    "dbname": os.getenv("DBNAME"),
    "user": "postgres",
    "password": os.getenv("PASSWORD"),
    "host": os.getenv("HOST"),
    "port": os.getenv("PORT"),
}


def execute_query(conn, query, params=None):
    with conn.cursor() as cursor:
        cursor.execute(query, params)
        conn.commit()


conn = psycopg2.connect(**db_config)


def add_to_db(table, data_add):
    check_query = sql.SQL(f"SELECT COUNT(*) FROM {table}")
    with conn.cursor() as cursor:
        cursor.execute(check_query)
        count = cursor.fetchone()[0]

    if count != 0:
        return

    for values in data_add:
        val = ", ".join(["%s"] * len(values.values()))
        insert_query = sql.SQL(
            f"""
            INSERT INTO {table} ({', '.join(list(values.keys()))})
            VALUES ({val})
        """
        )

        execute_query(conn, insert_query, list(values.values()))


data_add = {
    "users": (
        {
            "fullname": "string",
            "description": "string",
            "username": "string",
            "password": bytes(hash_password(os.getenv("string_PASSWORD"))),
            "is_admin": True,
            "is_parsing": False,
        },
        {
            "fullname": "string_admin",
            "description": "string_admin",
            "username": "string_admin",
            "password": bytes(hash_password(os.getenv("string_admin_PASSWORD"))),
            "is_admin": True,
            "is_parsing": False,
        },
        {
            "fullname": "admin_fullname",
            "description": "admin_description",
            "username": "admin",
            "password": bytes(hash_password(os.getenv("ADMIN_PASSWORD"))),
            "is_admin": True,
            "is_parsing": False,
        },
        {
            "fullname": "newuser_fullname",
            "description": "newuser_description",
            "username": "newuser",
            "password": bytes(hash_password(os.getenv("NEWUSER_PASSWORD"))),
            "is_admin": True,
            "is_parsing": False,
        },
        {
            "fullname": "simpleuser_fullname",
            "description": "simpleuser_description",
            "username": "simpleuser",
            "password": bytes(hash_password(os.getenv("SIMPLE_PASSWORD"))),
            "is_admin": False,
            "is_parsing": False,
        },
    ),
}

add_to_db("users", data_add["users"])

check_query1 = sql.SQL("SELECT id FROM users WHERE username = 'admin'")
check_query2 = sql.SQL("SELECT id FROM users WHERE username = 'newuser'")
check_query3 = sql.SQL("SELECT id FROM users WHERE username = 'simpleuser'")
with conn.cursor() as cursor:
    cursor.execute(check_query1)
    try:
        id_admin_fullname = cursor.fetchone()[0]
    except:
        id_admin_fullname = None
    cursor.execute(check_query2)
    try:
        id_newuser_fullname = cursor.fetchone()[0]
    except:
        id_newuser_fullname = None 
    cursor.execute(check_query3)
    try:
        id_simpleuser_fullname = cursor.fetchone()[0]
    except:
        id_simpleuser_fullname = None


newfilters = []
if id_admin_fullname:
    fil = [{
            "deep_filter": "11",
            "deep_analog": "10",
            "analog": False,
            "is_bigger": False,
            "date": "10",
            "logo": "RMFZ",
            "user_id": id_admin_fullname,
            "title": "string9",
            "pickup_point": "38760",
        },
        {
            "deep_filter": "11",
            "deep_analog": "10",
            "analog": False,
            "is_bigger": False,
            "date": "10",
            "logo": "RMFZ",
            "user_id": id_admin_fullname,
            "title": "string10",
            "pickup_point": "38760",
        },
        {
            "deep_filter": "10",
            "deep_analog": "10",
            "analog": False,
            "is_bigger": True,
            "date": "5",
            "logo": "HXAW",
            "user_id": id_admin_fullname,
            "title": "string1",
            "pickup_point": "38760",
        }]

    for i in fil:
        newfilters.append(i)

if id_newuser_fullname:
    fil = [
        {
            "deep_filter": "50",
            "deep_analog": "25",
            "analog": False,
            "is_bigger": False,
            "date": "25",
            "logo": "MARO",
            "user_id": id_newuser_fullname,
            "title": "string2",
            "pickup_point": "38760",
        },
        {
            "deep_filter": "11",
            "deep_analog": "23",
            "analog": False,
            "is_bigger": True,
            "date": "5",
            "logo": "OEOL",
            "user_id": id_newuser_fullname,
            "title": "string7",
            "pickup_point": "38760",
        },
        {
            "deep_filter": "11",
            "deep_analog": "10",
            "analog": False,
            "is_bigger": False,
            "date": "10",
            "logo": "OEOL",
            "user_id": id_newuser_fullname,
            "title": "string8",
            "pickup_point": "38760",
        },
    ]

    for i in fil:
        newfilters.append(i)

if id_simpleuser_fullname:
    fil = [
 {
            "deep_filter": "15",
            "deep_analog": "25",
            "analog": True,
            "is_bigger": False,
            "date": "25",
            "logo": "RXGF",
            "user_id": id_simpleuser_fullname,
            "title": "string3",
            "pickup_point": "38760",
        },
        {
            "deep_filter": "10",
            "deep_analog": "25",
            "analog": False,
            "is_bigger": False,
            "date": "25",
            "logo": "RXGF",
            "user_id": id_simpleuser_fullname,
            "title": "string4",
            "pickup_point": "38760",
        },
        {
            "deep_filter": "12",
            "deep_analog": "1",
            "analog": False,
            "logo": "RXGF",
            "user_id": id_simpleuser_fullname,
            "title": "string5",
            "pickup_point": "38760",
        },
        {
            "deep_filter": "33",
            "deep_analog": "31",
            "analog": False,
            "logo": "RXGF",
            "user_id": id_simpleuser_fullname,
            "title": "string6",
            "pickup_point": "38760",
        },
    ]

    for i in fil:
        newfilters.append(i)

data_add = {
    "newfilters": newfilters
}

add_to_db("newfilters", data_add["newfilters"])

check_query4 = sql.SQL("SELECT id FROM newfilters WHERE title = 'string2'")
check_query5 = sql.SQL("SELECT id FROM newfilters WHERE title = 'string9'")
with conn.cursor() as cursor:
    cursor.execute(check_query4)
    try:
        id_string2_filter = cursor.fetchone()[0]
    except:
        id_string2_filter = None
    cursor.execute(check_query5)
    try:
        id_string9_filter = cursor.fetchone()[0]
    except:
        id_string9_filter = None
for filename in ("test1_дляпарсинг.xlsx", "test2_послепарсинга.xlsx"):
    with open(str(settings.upload.path_for_upload) + "/" + filename, "w") as file:
        file.write("hello world")
        file.close()

data_add = {
    "files": [
        {
            "before_parsing_filename": "test1_дляпарсинг.xlsx",
            "after_parsing_filename": None,
            "date": str(datetime.now()),
            "user_id": id_admin_fullname,
        },
        {
            "before_parsing_filename": "test1_дляпарсинг.xlsx",
            "after_parsing_filename": None,
            "date": str(datetime.now()),
            "user_id": id_newuser_fullname,
        },
        {
            "before_parsing_filename": "test1_дляпарсинг.xlsx",
            "after_parsing_filename": None,
            "date": str(datetime.now()),
            "user_id": id_simpleuser_fullname,
        },
        {
            "before_parsing_filename": "test3_дляпарсинг.xlsx",
            "after_parsing_filename": None,
            "date": str(datetime.now()),
            "user_id": id_admin_fullname,
        },
        {
            "before_parsing_filename": "test3_дляпарсинг.xlsx",
            "after_parsing_filename": None,
            "date": str(datetime.now()),
            "user_id": id_newuser_fullname,
        },
        {
            "before_parsing_filename": "test3_дляпарсинг.xlsx",
            "after_parsing_filename": None,
            "date": str(datetime.now()),
            "user_id": id_admin_fullname,
        },
        {
            "before_parsing_filename": "test3_дляпарсинг.xlsx",
            "after_parsing_filename": None,
            "date": str(datetime.now()),
            "user_id": id_simpleuser_fullname,
        },
    ],
    "parsers": (
        {
            "article": "test_article",
            "name": "test_name",
            "brand": "test_brand",
            "article1": "test_article1",
            "quantity": "test_quantity",
            "price": "test_price",
            "batch": "test_batch",
            "nds": "test_NDS",
            "best_price": "test_bestPrice",
            "logo": "test_logo",
            "delivery_time": "test_deliveryTime",
            "new_price": "test_newPrice",
            "quantity1": "test_quantity1",
            "user_id": id_admin_fullname,
            "file_id": 1,
        },
        {
            "article": "test_article",
            "name": "test_name",
            "brand": "test_brand",
            "article1": "test_article1",
            "quantity": "test_quantity",
            "price": "test_price",
            "batch": "test_batch",
            "nds": "test_NDS",
            "best_price": "test_bestPrice",
            "logo": "test_logo",
            "delivery_time": "test_deliveryTime",
            "new_price": "test_newPrice",
            "quantity1": "test_quantity1",
            "user_id": id_admin_fullname,
            "file_id": 1,
        },
        {
            "article": "test_article",
            "name": "test_name",
            "brand": "test_brand",
            "article1": "test_article1",
            "quantity": "test_quantity",
            "price": "test_price",
            "batch": "test_batch",
            "nds": "test_NDS",
            "best_price": "test_bestPrice",
            "logo": "test_logo",
            "delivery_time": "test_deliveryTime",
            "new_price": "test_newPrice",
            "quantity1": "test_quantity1",
            "user_id": id_admin_fullname,
            "file_id": 1,
        },
        {
            "article": "test_article",
            "name": "test_name",
            "brand": "test_brand",
            "article1": "test_article1",
            "quantity": "test_quantity",
            "price": "test_price",
            "batch": "test_batch",
            "nds": "test_NDS",
            "best_price": "test_bestPrice",
            "logo": "test_logo",
            "delivery_time": "test_deliveryTime",
            "new_price": "test_newPrice",
            "quantity1": "test_quantity1",
            "user_id": id_admin_fullname,
            "file_id": 1,
        },
        {
            "article": "test_article",
            "name": "test_name",
            "brand": "test_brand",
            "article1": "test_article1",
            "quantity": "test_quantity",
            "price": "test_price",
            "batch": "test_batch",
            "nds": "test_NDS",
            "best_price": "test_bestPrice",
            "logo": "test_logo",
            "delivery_time": "test_deliveryTime",
            "new_price": "test_newPrice",
            "quantity1": "test_quantity1",
            "user_id": id_admin_fullname,
            "file_id": 1,
        },
        {
            "article": "test_article",
            "name": "test_name",
            "brand": "test_brand",
            "article1": "test_article1",
            "quantity": "test_quantity",
            "price": "test_price",
            "batch": "test_batch",
            "nds": "test_NDS",
            "best_price": "test_bestPrice",
            "logo": "test_logo",
            "delivery_time": "test_deliveryTime",
            "new_price": "test_newPrice",
            "quantity1": "test_quantity1",
            "user_id": id_admin_fullname,
            "file_id": 1,
        },
        {
            "article": "test_article",
            "name": "test_name",
            "brand": "test_brand",
            "article1": "test_article1",
            "quantity": "test_quantity",
            "price": "test_price",
            "batch": "test_batch",
            "nds": "test_NDS",
            "best_price": "test_bestPrice",
            "logo": "test_logo",
            "delivery_time": "test_deliveryTime",
            "new_price": "test_newPrice",
            "quantity1": "test_quantity1",
            "user_id": id_admin_fullname,
            "file_id": 1,
        },
        {
            "article": "test_article",
            "name": "test_name",
            "brand": "test_brand",
            "article1": "test_article1",
            "quantity": "test_quantity",
            "price": "test_price",
            "batch": "test_batch",
            "nds": "test_NDS",
            "best_price": "test_bestPrice",
            "logo": "test_logo",
            "delivery_time": "test_deliveryTime",
            "new_price": "test_newPrice",
            "quantity1": "test_quantity1",
            "user_id": id_admin_fullname,
            "file_id": 1,
        },
        {
            "article": "test_article",
            "name": "test_name",
            "brand": "test_brand",
            "article1": "test_article1",
            "quantity": "test_quantity",
            "price": "test_price",
            "batch": "test_batch",
            "nds": "test_NDS",
            "best_price": "test_bestPrice",
            "logo": "test_logo",
            "delivery_time": "test_deliveryTime",
            "new_price": "test_newPrice",
            "quantity1": "test_quantity1",
            "user_id": id_newuser_fullname,
            "file_id": 1,
        },
        {
            "article": "test_article",
            "name": "test_name",
            "brand": "test_brand",
            "article1": "test_article1",
            "quantity": "test_quantity",
            "price": "test_price",
            "batch": "test_batch",
            "nds": "test_NDS",
            "best_price": "test_bestPrice",
            "logo": "test_logo",
            "delivery_time": "test_deliveryTime",
            "new_price": "test_newPrice",
            "quantity1": "test_quantity1",
            "user_id": id_newuser_fullname,
            "file_id": 1,
        },
        {
            "article": "test_article",
            "name": "test_name",
            "brand": "test_brand",
            "article1": "test_article1",
            "quantity": "test_quantity",
            "price": "test_price",
            "batch": "test_batch",
            "nds": "test_NDS",
            "best_price": "test_bestPrice",
            "logo": "test_logo",
            "delivery_time": "test_deliveryTime",
            "new_price": "test_newPrice",
            "quantity1": "test_quantity1",
            "user_id": id_newuser_fullname,
            "file_id": 1,
        },
        {
            "article": "test_article",
            "name": "test_name",
            "brand": "test_brand",
            "article1": "test_article1",
            "quantity": "test_quantity",
            "price": "test_price",
            "batch": "test_batch",
            "nds": "test_NDS",
            "best_price": "test_bestPrice",
            "logo": "test_logo",
            "delivery_time": "test_deliveryTime",
            "new_price": "test_newPrice",
            "quantity1": "test_quantity1",
            "user_id": id_newuser_fullname,
            "file_id": 1,
        },
        {
            "article": "test_article",
            "name": "test_name",
            "brand": "test_brand",
            "article1": "test_article1",
            "quantity": "test_quantity",
            "price": "test_price",
            "batch": "test_batch",
            "nds": "test_NDS",
            "best_price": "test_bestPrice",
            "logo": "test_logo",
            "delivery_time": "test_deliveryTime",
            "new_price": "test_newPrice",
            "quantity1": "test_quantity1",
            "user_id": id_newuser_fullname,
            "file_id": 1,
        },
        {
            "article": "test_article",
            "name": "test_name",
            "brand": "test_brand",
            "article1": "test_article1",
            "quantity": "test_quantity",
            "price": "test_price",
            "batch": "test_batch",
            "nds": "test_NDS",
            "best_price": "test_bestPrice",
            "logo": "test_logo",
            "delivery_time": "test_deliveryTime",
            "new_price": "test_newPrice",
            "quantity1": "test_quantity1",
            "user_id": id_newuser_fullname,
            "file_id": 1,
        },
        {
            "article": "test_article",
            "name": "test_name",
            "brand": "test_brand",
            "article1": "test_article1",
            "quantity": "test_quantity",
            "price": "test_price",
            "batch": "test_batch",
            "nds": "test_NDS",
            "best_price": "test_bestPrice",
            "logo": "test_logo",
            "delivery_time": "test_deliveryTime",
            "new_price": "test_newPrice",
            "quantity1": "test_quantity1",
            "user_id": id_simpleuser_fullname,
            "file_id": 1,
        },
        {
            "article": "test_article",
            "name": "test_name",
            "brand": "test_brand",
            "article1": "test_article1",
            "quantity": "test_quantity",
            "price": "test_price",
            "batch": "test_batch",
            "nds": "test_NDS",
            "best_price": "test_bestPrice",
            "logo": "test_logo",
            "delivery_time": "test_deliveryTime",
            "new_price": "test_newPrice",
            "quantity1": "test_quantity1",
            "user_id": id_simpleuser_fullname,
            "file_id": 1,
        },
        {
            "article": "test_article",
            "name": "test_name",
            "brand": "test_brand",
            "article1": "test_article1",
            "quantity": "test_quantity",
            "price": "test_price",
            "batch": "test_batch",
            "nds": "test_NDS",
            "best_price": "test_bestPrice",
            "logo": "test_logo",
            "delivery_time": "test_deliveryTime",
            "new_price": "test_newPrice",
            "quantity1": "test_quantity1",
            "user_id": id_simpleuser_fullname,
            "file_id": 1,
        },
        {
            "article": "test_article",
            "name": "test_name",
            "brand": "test_brand",
            "article1": "test_article1",
            "quantity": "test_quantity",
            "price": "test_price",
            "batch": "test_batch",
            "nds": "test_NDS",
            "best_price": "test_bestPrice",
            "logo": "test_logo",
            "delivery_time": "test_deliveryTime",
            "new_price": "test_newPrice",
            "quantity1": "test_quantity1",
            "user_id": id_simpleuser_fullname,
            "file_id": 1,
        },
        {
            "article": "test_article",
            "name": "test_name",
            "brand": "test_brand",
            "article1": "test_article1",
            "quantity": "test_quantity",
            "price": "test_price",
            "batch": "test_batch",
            "nds": "test_NDS",
            "best_price": "test_bestPrice",
            "logo": "test_logo",
            "delivery_time": "test_deliveryTime",
            "new_price": "test_newPrice",
            "quantity1": "test_quantity1",
            "user_id": id_simpleuser_fullname,
            "file_id": 1,
        },
        {
            "article": "test_article",
            "name": "test_name",
            "brand": "test_brand",
            "article1": "test_article1",
            "quantity": "test_quantity",
            "price": "test_price",
            "batch": "test_batch",
            "nds": "test_NDS",
            "best_price": "test_bestPrice",
            "logo": "test_logo",
            "delivery_time": "test_deliveryTime",
            "new_price": "test_newPrice",
            "quantity1": "test_quantity1",
            "user_id": id_simpleuser_fullname,
            "file_id": 1,
        },
    ),
    "proxys": (
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "1",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://45.81.76.140:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "2",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://45.81.79.203:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "3",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://45.81.79.2:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "4",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://94.127.136.44:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "5",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://195.19.200.161:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "6",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://193.232.103.48:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "7",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://195.19.200.10:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "8",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://195.19.200.184:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "9",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.46.78:9323",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "10",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.45.154:9121",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "11",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.47.248:9822",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "12",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.47.7:9788",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "13",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.47.195:9378",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "14",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.46.40:9878",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "15",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.46.80:9001",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "16",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.47.91:9243",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "17",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.47.202:9797",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "18",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.44.35:9409",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "19",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.47.66:9832",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "20",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.46.117:9948",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "21",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://194.67.199.154:9781",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "22",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://194.67.202.84:9691",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "23",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://194.67.217.226:9388",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "24",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://194.67.222.7:9945",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "25",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://194.67.217.177:9409",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "26",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://194.67.219.3:9247",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "27",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://194.67.216.233:9018",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "28",
            "login": os.getenv("login3_proxy"),
            "password": os.getenv("password3_proxy"),
            "ip_with_port": "http://45.128.130.160:3205",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "29",
            "login": os.getenv("login3_proxy"),
            "password": os.getenv("password3_proxy"),
            "ip_with_port": "http://194.32.126.144:3205",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "30",
            "login": os.getenv("login3_proxy"),
            "password": os.getenv("password3_proxy"),
            "ip_with_port": "http://45.11.22.246:3205",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "31",
            "login": os.getenv("login3_proxy"),
            "password": os.getenv("password3_proxy"),
            "ip_with_port": "http://212.107.24.86:3205",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-10 15:25:55",
            "id_proxy": "32",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://45.81.76.140:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-10 15:25:55",
            "id_proxy": "33",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://45.81.79.203:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-10 15:25:55",
            "id_proxy": "34",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://45.81.79.2:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-10 15:25:55",
            "id_proxy": "35",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://94.127.136.44:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-10 15:25:55",
            "id_proxy": "36",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://195.19.200.161:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-10 15:25:55",
            "id_proxy": "37",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://193.232.103.48:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-10 15:25:55",
            "id_proxy": "38",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://195.19.200.10:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-10 15:25:55",
            "id_proxy": "39",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://195.19.200.184:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-11-24 23:08:00",
            "id_proxy": "40",
            "login": os.getenv("login5_proxy"),
            "password": os.getenv("password5_proxy"),
            "ip_with_port": "http://45.143.247.157:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-11-24 22:24:00",
            "id_proxy": "41",
            "login": "kEf6bm",
            "password": "9t04vj",
            "ip_with_port": "http://168.80.1.218:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-25 22:22:00",
            "id_proxy": "42",
            "login": "qYZ6BL",
            "password": "vrxpY6",
            "ip_with_port": "http://168.80.1.7:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-25 22:21:00",
            "id_proxy": "43",
            "login": "NXQb0G",
            "password": "Sjz1UE",
            "ip_with_port": "http://168.81.57.53:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-25 22:01:00",
            "id_proxy": "44",
            "login": "u7yY0o",
            "password": "M20nKa",
            "ip_with_port": "http://168.81.59.243:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },

        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "1",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://45.81.76.140:8000",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "2",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://45.81.79.203:8000",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "3",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://45.81.79.2:8000",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "4",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://94.127.136.44:8000",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "5",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://195.19.200.161:8000",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "6",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://193.232.103.48:8000",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "7",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://195.19.200.10:8000",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "8",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://195.19.200.184:8000",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "9",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.46.78:9323",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "10",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.45.154:9121",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "11",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.47.248:9822",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "12",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.47.7:9788",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "13",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.47.195:9378",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "14",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.46.40:9878",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "15",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.46.80:9001",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "16",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.47.91:9243",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "17",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.47.202:9797",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "18",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.44.35:9409",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "19",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.47.66:9832",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "20",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://46.161.46.117:9948",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "21",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://194.67.199.154:9781",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "22",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://194.67.202.84:9691",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "23",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://194.67.217.226:9388",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "24",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://194.67.222.7:9945",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "25",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://194.67.217.177:9409",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "26",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://194.67.219.3:9247",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "27",
            "login": os.getenv("login4_proxy"),
            "password": os.getenv("password4_proxy"),
            "ip_with_port": "http://194.67.216.233:9018",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "28",
            "login": os.getenv("login3_proxy"),
            "password": os.getenv("password3_proxy"),
            "ip_with_port": "http://45.128.130.160:3205",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "29",
            "login": os.getenv("login3_proxy"),
            "password": os.getenv("password3_proxy"),
            "ip_with_port": "http://194.32.126.144:3205",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "30",
            "login": os.getenv("login3_proxy"),
            "password": os.getenv("password3_proxy"),
            "ip_with_port": "http://45.11.22.246:3205",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-13 15:51:55",
            "id_proxy": "31",
            "login": os.getenv("login3_proxy"),
            "password": os.getenv("password3_proxy"),
            "ip_with_port": "http://212.107.24.86:3205",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-10 15:25:55",
            "id_proxy": "32",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://45.81.76.140:8000",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-10 15:25:55",
            "id_proxy": "33",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://45.81.79.203:8000",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-10 15:25:55",
            "id_proxy": "34",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://45.81.79.2:8000",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-10 15:25:55",
            "id_proxy": "35",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://94.127.136.44:8000",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-10 15:25:55",
            "id_proxy": "36",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://195.19.200.161:8000",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-10 15:25:55",
            "id_proxy": "37",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://193.232.103.48:8000",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-10 15:25:55",
            "id_proxy": "38",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://195.19.200.10:8000",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-10-10 15:25:55",
            "id_proxy": "39",
            "login": os.getenv("login2_proxy"),
            "password": os.getenv("password2_proxy"),
            "ip_with_port": "http://195.19.200.184:8000",
            "_is_banned": False,
            "user_id": id_simpleuser_fullname,
            "is_using": True,
        },
        {
            "expired_at": "2024-11-24 23:08:00", #тестовое
            "id_proxy": "40",
            "login": "LSZ1Xb",
            "password": "heLL19",
            "ip_with_port": "http://45.143.247.157:8000",
            "_is_banned": False,
            "user_id": id_admin_fullname,
            "is_using": True,
        },
    ),
}

if not id_string2_filter is None:
    data_add["files"].append(        {
            "before_parsing_filename": "test2_дляпарсинг.xlsx",
            "after_parsing_filename": "test2_послепарсинга.xlsx",
            "date": str(datetime.now()),
            "user_id": id_newuser_fullname,
            "new_filter_id": id_string2_filter,
        },)
    data_add["files"].append(
        {
            "before_parsing_filename": "test2_дляпарсинг.xlsx",
            "after_parsing_filename": "test2_послепарсинга.xlsx",
            "date": str(datetime.now()),
            "user_id": id_newuser_fullname,
            "new_filter_id": id_string2_filter,
        },
    )

if not id_string9_filter is None:
    data_add["files"].append(        
        {
            "before_parsing_filename": "test2_дляпарсинг.xlsx",
            "after_parsing_filename": "test2_послепарсинга.xlsx",
            "date": str(datetime.now()),
            "user_id": id_admin_fullname,
            "new_filter_id": id_string9_filter,
        },
    )

for name in ("files", "proxys", "parsers"):
    data = data_add[name]
    for val in (id_admin_fullname, id_simpleuser_fullname, id_simpleuser_fullname, id_newuser_fullname):
        if val is None:
            data = [dat for dat in data if dat["user_id"] != val]
        
    data_add[name] = data

for table in tables:
    add_to_db(table, data_add[table])
